-- PR-A.5: seed legit_check_reference_photos with 100 photos (50 models × 2).
-- Photos scraped from Bing Images via Playwright + Chrome CDP and uploaded to
-- Supabase Storage bucket `legit-references` (public). Migration is idempotent
-- (UNIQUE constraint + ON CONFLICT DO NOTHING). Uses slug-based subqueries for
-- model_id resolution so a fresh DB with a different SERIAL ordering still seeds correctly.

-- Step 1: add UNIQUE constraint per Devin Review #15 (prevents duplicate uploads).
-- Wrapped in DO block because PostgreSQL has no `ADD CONSTRAINT IF NOT EXISTS`.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'legit_check_reference_photos_model_url_unique'
  ) THEN
    ALTER TABLE legit_check_reference_photos
      ADD CONSTRAINT legit_check_reference_photos_model_url_unique
      UNIQUE (model_id, photo_url);
  END IF;
END $$;

-- Step 2: insert seed rows. model_id resolved via slug to survive SERIAL gaps
-- or out-of-order inserts on fresh databases (defensive vs hardcoded ids).
INSERT INTO legit_check_reference_photos (model_id, photo_url, angle, focus, source, source_url, ordering)
SELECT m.id, v.photo_url, v.angle, v.focus, v.source, v.source_url, v.ordering
FROM (VALUES
  ('adidas', 'campus-00s', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/campus-00s/1.jpg', 'front', NULL::text, 'bing-images', 'https://assets.adidas.com/images/w_1880,f_auto,q_auto/3c3e53aaaeaf4273864baf7b00b3047a_9366/H03471_41_detail.jpg', 1),
  ('adidas', 'campus-00s', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/campus-00s/2.webp', 'alt', NULL::text, 'bing-images', 'https://levelshoes.co.za/cdn/shop/files/pixelcut-export-1711964904522.png?v=1711965264', 2),
  ('adidas', 'forum-low', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/forum-low/1.jpg', 'front', NULL::text, 'bing-images', 'https://images.stockx.com/images/adidas-Forum-Low-CL-Cream-White-Dark-Blue.jpg?fit=fill&bg=FFFFFF&w=576&h=384&q=41&dpr=3&trim=color&updated_at=1730913017', 1),
  ('adidas', 'forum-low', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/forum-low/2.jpg', 'alt', NULL::text, 'bing-images', 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/4e4b03ef7eef4ef5b610841fd4e90e7c_9366/Forum_84_Low_Shoes_White_IE9935_01_standard.jpg', 2),
  ('adidas', 'gazelle-indoor', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/gazelle-indoor/1.jpg', 'front', NULL::text, 'bing-images', 'https://assets.adidas.com/images/w_940,f_auto,q_auto/1e936302ec8e46d9ac2d8168bcbdeda2_9366/JI2062_HM53.jpg', 1),
  ('adidas', 'gazelle-indoor', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/gazelle-indoor/2.jpg', 'alt', NULL::text, 'bing-images', 'https://assets.adidas.com/images/w_1880,f_auto,q_auto/a047f4afe81e4a0586bb2de308665a05_9366/IG4994_42_detail.jpg', 2),
  ('adidas', 'samba-og', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/samba-og/1.jpg', 'front', NULL::text, 'bing-images', 'https://assets.adidas.com/images/w_940,f_auto,q_auto/59185f5309924579ad0a0ca8a5c8d681_9366/ID2056_04_standard.jpg', 1),
  ('adidas', 'samba-og', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/samba-og/2.jpg', 'alt', NULL::text, 'bing-images', 'https://assets.adidas.com/images/w_1880,f_auto,q_auto/4c70105150234ac4b948a8bf01187e0c_9366/B75807_01_standard.jpg', 2),
  ('adidas', 'stan-smith', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/stan-smith/1.jpg', 'front', NULL::text, 'bing-images', 'https://media-www.sportchek.ca/product/div-05-footwear/dpt-80-footwear/sdpt-01-mens/333957212/adidas-stan-smith-white-red-423-m-3cb4f36d-b845-49a3-8d3c-ca243bc0787b-jpgrendition.jpg?imdensity=1&imwidth=1244&impolicy=gZoom', 1),
  ('adidas', 'stan-smith', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/stan-smith/2.jpg', 'alt', NULL::text, 'bing-images', 'https://assets.adidas.com/images/w_940,f_auto,q_auto/538c782b646c485abf811522b3f77300_9366/IE0469_41_detail.jpg', 2),
  ('adidas', 'superstar', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/superstar/1.jpg', 'front', NULL::text, 'bing-images', 'https://assets.adidas.com/images/w_1880,f_auto,q_auto/a24dfc935fa64204b7c655f17b4b7eb2_9366/JP9678_04_standard.jpg', 1),
  ('adidas', 'superstar', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/superstar/2.jpg', 'alt', NULL::text, 'bing-images', 'https://assets.adidas.com/images/w_1880,f_auto,q_auto/b3fe3507630948dca02abb0dbe7d9d7c_9366/JI0124_04_standard.jpg', 2),
  ('adidas', 'yeezy-boost-350-v2', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/yeezy-boost-350-v2/1.webp', 'front', NULL::text, 'bing-images', 'https://sneakernews.com/wp-content/uploads/2023/05/adidas-yeezy-boost-350-v2-granite-hq2059-release-date-4.jpg', 1),
  ('adidas', 'yeezy-boost-350-v2', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/yeezy-boost-350-v2/2.webp', 'alt', NULL::text, 'bing-images', 'https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/075/775/178/original/924555_01.jpg.jpeg?action=crop&width=4000', 2),
  ('adidas', 'yeezy-boost-700', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/yeezy-boost-700/1.png', 'front', NULL::text, 'bing-images', 'https://www.yeezyadidas.us.com/wp-content/uploads/2024/03/93AF39C5-E9E4-B740-A7A3-8D3E5E14DD18.png', 1),
  ('adidas', 'yeezy-boost-700', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/yeezy-boost-700/2.jpg', 'alt', NULL::text, 'bing-images', 'https://www.newkick.org/image/cache/202106/Adidas/Yeezy/adidas-yeezy-boost-700-enflame-amber-gw0297/adidas-yeezy-boost-700-enflame-amber-gw0297-(1)-2600x2600.jpg', 2),
  ('adidas', 'yeezy-foam-runner', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/yeezy-foam-runner/1.jpg', 'front', NULL::text, 'bing-images', 'https://www.hypestateofficial.com/wp-content/uploads/2024/03/Adidas-Yeezy-Foam-RNR-MX-Granite-1.jpg', 1),
  ('adidas', 'yeezy-foam-runner', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/yeezy-foam-runner/2.webp', 'alt', NULL::text, 'bing-images', 'http://crepdogcrew.com/cdn/shop/files/foam2_12c96ec6-413c-43e3-91d8-3a02f8c8412e.png?v=1690992699&width=2048', 2),
  ('adidas', 'yeezy-slide', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/yeezy-slide/1.jpg', 'front', NULL::text, 'bing-images', 'https://media.sivasdescalzo.com/media/catalog/product/I/D/ID2350_sivasdescalzo-adidas_YEEZY-YZY_SLIDE-1691136623-2.jpg?width=1600', 1),
  ('adidas', 'yeezy-slide', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/adidas/yeezy-slide/2.jpg', 'alt', NULL::text, 'bing-images', 'https://images.stockx.com/images/adidas-Yeezy-Slide-Dark-Onyx-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&q=90&dpr=2&trim=color&updated_at=1710364038', 2),
  ('carhartt-wip', 'active-jacket', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/active-jacket/1.webp', 'front', NULL::text, 'bing-images', 'https://cdn.media.amplience.net/i/carhartt_wip/I032232_01_06-OF-01?%24OF%24=&fmt=auto&w=3840&qlt=default', 1),
  ('carhartt-wip', 'active-jacket', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/active-jacket/2.webp', 'alt', NULL::text, 'bing-images', 'https://media.endclothing.com/media/f_auto,q_auto:eco,w_1600/prodmedia/media/catalog/product/2/5/25-01-2024-JC_I032939-8902_6_1.jpg', 2),
  ('carhartt-wip', 'chase-sweatshirt', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/chase-sweatshirt/1.webp', 'front', NULL::text, 'bing-images', 'https://cdn.media.amplience.net/i/carhartt_wip/I033661_3H4_XX-ST-01?%24ST%24=&fmt=auto&w=3840&qlt=default', 1),
  ('carhartt-wip', 'chase-sweatshirt', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/chase-sweatshirt/2.webp', 'alt', NULL::text, 'bing-images', 'https://cdn.media.amplience.net/i/carhartt_wip/I033660_00W_XX-OF-02?%24OF%24=&fmt=auto&w=3840&qlt=default', 2),
  ('carhartt-wip', 'chase-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/chase-tee/1.webp', 'front', NULL::text, 'bing-images', 'https://media.endclothing.com/media/f_auto,q_auto:eco,w_1600/prodmedia/media/catalog/product/2/0/20-02-23-LS_I026391-1GSXX_10_1.jpg', 1),
  ('carhartt-wip', 'chase-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/chase-tee/2.webp', 'alt', NULL::text, 'bing-images', 'https://media.endclothing.com/media/f_auto,q_auto:eco,w_1600/prodmedia/media/catalog/product/2/3/23-05-2023-JB_I026391-1OFXX_1_1.jpg', 2),
  ('carhartt-wip', 'detroit-jacket', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/detroit-jacket/1.webp', 'front', NULL::text, 'bing-images', 'https://cdn.media.amplience.net/i/carhartt_wip/I035614_3CL_4O-ST-01?%24ST%24=&fmt=auto&w=3840&qlt=default', 1),
  ('carhartt-wip', 'detroit-jacket', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/detroit-jacket/2.webp', 'alt', NULL::text, 'bing-images', 'https://media.endclothing.com/media/f_auto,q_auto:eco,w_1600/prodmedia/media/catalog/product/1/2/12-09-24-NS2_I027358-2I73K_9_1.jpg', 2),
  ('carhartt-wip', 'kickflip-backpack', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/kickflip-backpack/1.webp', 'front', NULL::text, 'bing-images', 'https://cdn.media.amplience.net/i/carhartt_wip/I031468_38T_XX-ST-01?%24ST%24=&fmt=auto&w=3840&qlt=default', 1),
  ('carhartt-wip', 'kickflip-backpack', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/kickflip-backpack/2.jpg', 'alt', NULL::text, 'bing-images', 'https://maufeitio.pt/onlineshop/118998-thickbox_default/carhartt-wip-kickflip-backpack-black.jpg', 2),
  ('carhartt-wip', 'master-pant', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/master-pant/1.webp', 'front', NULL::text, 'bing-images', 'https://cdn.media.amplience.net/i/carhartt_wip/I034233_87_02-OF-04?%24OF%24=&fmt=auto&w=3840&qlt=default', 1),
  ('carhartt-wip', 'master-pant', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/master-pant/2.jpg', 'alt', NULL::text, 'bing-images', 'https://static.super-shop.com/1428233-carhartt-wip-master-pants-black.jpg?w=960', 2),
  ('carhartt-wip', 'og-active-vest', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/og-active-vest/1.jpg', 'front', NULL::text, 'bing-images', 'https://cdn.media.amplience.net/i/carhartt_wip/I035349_89_XX-OF-01?%24OF%24=&fmt=auto&w=3840&qlt=default', 1),
  ('carhartt-wip', 'og-active-vest', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/og-active-vest/2.jpg', 'alt', NULL::text, 'bing-images', 'https://static.ftshp.digital/img/p/1/6/2/2/5/2/7/1622527.jpg', 2),
  ('carhartt-wip', 'pocket-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/pocket-tee/1.webp', 'front', NULL::text, 'bing-images', 'https://media.sivasdescalzo.com/media/catalog/product/I/0/I030434-2BWXX_sivasdescalzo-Carhartt_WIP-S_S_POCKET_T-SHIRT-1720528954-1.jpg', 1),
  ('carhartt-wip', 'pocket-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/pocket-tee/2.webp', 'alt', NULL::text, 'bing-images', 'https://media.sivasdescalzo.com/media/catalog/product/I/0/I030434-1CXX_sivasdescalzo-Carhartt_WIP-S_S_POCKET_T-SHIRT-1738322327-4.jpg?width=1440&q=72&optimize=high&format=auto', 2),
  ('carhartt-wip', 'single-knee-pant', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/single-knee-pant/1.webp', 'front', NULL::text, 'bing-images', 'https://cdn.media.amplience.net/i/carhartt_wip/I031497_89_02-OF-02?%24OF%24=&fmt=auto&w=3840&qlt=default', 1),
  ('carhartt-wip', 'single-knee-pant', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/single-knee-pant/2.webp', 'alt', NULL::text, 'bing-images', 'https://media.endclothing.com/media/f_auto,q_auto:eco,w_1600/prodmedia/media/catalog/product/1/3/13-04-2023-AJ_I032024-0102_10_1.jpg', 2),
  ('carhartt-wip', 'watch-hat', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/watch-hat/1.webp', 'front', NULL::text, 'bing-images', 'https://cdn.media.amplience.net/i/carhartt_wip/I020222_11_XX-ST-01?%24ST%24=&fmt=auto&w=3840&qlt=default', 1),
  ('carhartt-wip', 'watch-hat', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/carhartt-wip/watch-hat/2.jpg', 'alt', NULL::text, 'bing-images', 'https://static.ftshp.digital/img/p/1/2/5/1/4/9/0/1251490.jpg', 2),
  ('nike', 'air-force-1-low', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-force-1-low/1.jpg', 'front', NULL::text, 'bing-images', 'https://images.stockx.com/images/Nike-Air-Force-1-07-Low-Jewel-Cool-Grey-Black.jpg?fit=fill&bg=FFFFFF&w=576&h=384&q=41&dpr=3&trim=color&updated_at=1731532339', 1),
  ('nike', 'air-force-1-low', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-force-1-low/2.jpg', 'alt', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/24458675-63c4-461d-a6cb-d11cdd08562e/NIKE+AIR+FORCE+1+%2707.png', 2),
  ('nike', 'air-jordan-1-high-og', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-jordan-1-high-og/1.jpg', 'front', NULL::text, 'bing-images', 'https://static.nike.com/a/images/w_1280,c_limit,q_auto,f_auto/0acb9f29-b23b-41a9-bbf6-f947ae71de99/air-jordan-1-high-og-black-toe-dz5485-106-release-date.jpg', 1),
  ('nike', 'air-jordan-1-high-og', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-jordan-1-high-og/2.jpg', 'alt', NULL::text, 'bing-images', 'https://static.nike.com/a/images/w_1280,c_limit,q_auto,f_auto/579e7039-8759-4d85-a4e6-47dc2864d046/air-jordan-1-high-og-black-toe-dz5485-106-release-date.jpg', 2),
  ('nike', 'air-jordan-1-low', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-jordan-1-low/1.jpg', 'front', NULL::text, 'bing-images', 'https://static.nike.com/a/images/w_1280,q_auto,f_auto/882c8d1f-2ff0-41ca-9d33-04438ab90473/air-jordan-1-low-og-chicago-hq6998-600-release-date.jpg', 1),
  ('nike', 'air-jordan-1-low', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-jordan-1-low/2.webp', 'alt', NULL::text, 'bing-images', 'https://media.sivasdescalzo.com/media/catalog/product/D/C/DC0774-200_sivasdescalzo-Jordan-WMNS_AIR_JORDAN_1_LOW-1693474077-2.jpg?quality=70&auto=webp&fit=bounds&width=', 2),
  ('nike', 'air-jordan-1-mid', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-jordan-1-mid/1.jpg', 'front', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png', 1),
  ('nike', 'air-jordan-1-mid', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-jordan-1-mid/2.jpg', 'alt', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/3b14fa48-f61f-4c57-a875-e14d6aa51a54/air-jordan-1-mid-shoes-f8W9ns.png', 2),
  ('nike', 'air-max-90', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-max-90/1.jpg', 'front', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_web_pw_592_v2/f_auto/062c378c-8a27-4405-9c82-12373a44c1ff/WMNS+AIR+MAX+90.png', 1),
  ('nike', 'air-max-90', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-max-90/2.jpg', 'alt', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_web_pw_592_v2/f_auto/7a5b9a2b-08b7-48ec-80f6-29d18c07a4bc/NIKE+AIR+MAX+90+PRM.png', 2),
  ('nike', 'air-max-95', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-max-95/1.jpg', 'front', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_web_pw_592_v2/f_auto/75629f9f-da7a-4ed7-9ba4-1137179d4028/W+NIKE+AIR+MAX+95+BIG+BUBBLE.png', 1),
  ('nike', 'air-max-95', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-max-95/2.jpg', 'alt', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/69107e64-9c7e-4f4c-b36e-db688e84dd44/NIKE+AIR+MAX+95+BIG+BUBBLE.png', 2),
  ('nike', 'air-max-97', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-max-97/1.jpg', 'front', NULL::text, 'bing-images', 'https://www.sportsdirect.com/images/imgzoom/12/12327103_xxl_a2.jpg', 1),
  ('nike', 'air-max-97', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/air-max-97/2.jpg', 'alt', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/df443480-9bcb-4cfe-ae1b-db793a405fda/air-max-97-shoes-xXlgnF.png', 2),
  ('nike', 'cortez', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/cortez/1.jpg', 'front', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_web_pw_592_v2/f_auto/734a4eb2-bcb0-467e-b43f-76c471be16e5/W+NIKE+CORTEZ.png', 1),
  ('nike', 'cortez', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/cortez/2.jpg', 'alt', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_web_pw_592_v2/f_auto/6fdb88bf-386c-4f74-9e05-2b33bb10b3f2/NIKE+CORTEZ.png', 2),
  ('nike', 'dunk-high', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/dunk-high/1.jpg', 'front', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_web_pw_592_v2/f_auto/097da82e-24e8-413d-b521-08c4109edb52/W+NIKE+DUNK+HIGH+NN.png', 1),
  ('nike', 'dunk-high', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/dunk-high/2.jpg', 'alt', NULL::text, 'bing-images', 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/097da82e-24e8-413d-b521-08c4109edb52/W+NIKE+DUNK+HIGH+NN.png', 2),
  ('nike', 'dunk-low', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/dunk-low/1.jpg', 'front', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_web_pw_592_v2/f_auto/e7494e1f-2f02-4b47-a016-5097e1b81989/W+NIKE+DUNK+LOW.png', 1),
  ('nike', 'dunk-low', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/nike/dunk-low/2.jpg', 'alt', NULL::text, 'bing-images', 'https://static.nike.com/a/images/t_web_pw_592_v2/f_auto/7634f295-ce70-474c-8d24-8654b2ab3412/NIKE+DUNK+LOW+RETRO.png', 2),
  ('stone-island', 'cargo-pants', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/cargo-pants/1.jpg', 'front', NULL::text, 'bing-images', 'https://image-cdn.hypb.st/https://s3.store.hypebeast.com/media/image/28/a6/pants-9-1-1d665.jpg?fit=max&w=720&q=90', 1),
  ('stone-island', 'cargo-pants', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/cargo-pants/2.webp', 'alt', NULL::text, 'bing-images', 'https://drake-store-shop.ch/9020-large_default/stone-island-cargo-pants.jpg', 2),
  ('stone-island', 'compass-patch-hoodie', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/compass-patch-hoodie/1.webp', 'front', NULL::text, 'bing-images', 'https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/103/586/074/original/1472214_01.jpg.jpeg?action=crop&width=750', 1),
  ('stone-island', 'compass-patch-hoodie', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/compass-patch-hoodie/2.jpg', 'alt', NULL::text, 'bing-images', 'https://cdn2.jomashop.com/media/catalog/product/s/t/stone-island-compass-patch-garment-dyed-zipup-hoodie-801564251a0m64melange-grey_1.jpg', 2),
  ('stone-island', 'compass-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/compass-tee/1.jpg', 'front', NULL::text, 'bing-images', 'https://www.circle-fashion.com/images/compass-logo-t-shirt-p50665-110378_image.jpg', 1),
  ('stone-island', 'compass-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/compass-tee/2.jpg', 'alt', NULL::text, 'bing-images', 'https://down-id.img.susercontent.com/file/id-11134207-7r990-lskdchsswuzd3e', 2),
  ('stone-island', 'garment-dyed-crewneck', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/garment-dyed-crewneck/1.webp', 'front', NULL::text, 'bing-images', 'https://cdn.clothbase.com/uploads/f2deaf2b-b7a3-42f8-9413-fe7c6c58d862/16-03-23-TC_101563051-A0029_7_1.jpg', 1),
  ('stone-island', 'garment-dyed-crewneck', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/garment-dyed-crewneck/2.webp', 'alt', NULL::text, 'bing-images', 'https://cdn.clothbase.com/uploads/c12b1986-2097-45ad-a320-8c14fd906d4f/15-03-23-TC_101563051-V0065_1_1.jpg', 2),
  ('stone-island', 'hooded-down-jacket', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/hooded-down-jacket/1.jpg', 'front', NULL::text, 'bing-images', 'https://cdn.clothbase.com/uploads/b0ed8c64-9f70-4499-9537-2789350b5c16/image.jpg', 1),
  ('stone-island', 'hooded-down-jacket', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/hooded-down-jacket/2.webp', 'alt', NULL::text, 'bing-images', 'https://media.endclothing.com/media/f_auto,q_auto:eco,w_1600/prodmedia/media/catalog/product/1/4/14-02-2024-aj_801540124-v0029_1.jpg', 2),
  ('stone-island', 'marina-plated-sweatshirt', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/marina-plated-sweatshirt/1.webp', 'front', NULL::text, 'bing-images', 'https://media.endclothing.com/media/f_auto,q_auto:eco,w_1600/prodmedia/media/catalog/product/0/3/03-05-2024-AJ_8015614X2-V0127_1_1.jpg', 1),
  ('stone-island', 'marina-plated-sweatshirt', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/marina-plated-sweatshirt/2.webp', 'alt', NULL::text, 'bing-images', 'https://media.endclothing.com/media/f_auto,q_auto:eco,w_1600/prodmedia/media/catalog/product/1/0/10-08-2024-JD_8115638X5-V0022_10_1.jpg', 2),
  ('stone-island', 'naslan-light-jacket', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/naslan-light-jacket/1.webp', 'front', NULL::text, 'bing-images', 'https://www.garmzfactory.com/cdn/shop/files/stone-island-naslan-light-watro-hooded-jacket-green-1_1024x.jpg?v=1704737962', 1),
  ('stone-island', 'naslan-light-jacket', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/naslan-light-jacket/2.webp', 'alt', NULL::text, 'bing-images', 'https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/075/128/003/original/1003299_01.jpg.jpeg?width=750', 2),
  ('stone-island', 'reflective-knit-hat', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/reflective-knit-hat/1.jpg', 'front', NULL::text, 'bing-images', 'https://caveosaka.com/html/upload/save_image/0725102910_6882dde67b0cb.jpeg', 1),
  ('stone-island', 'reflective-knit-hat', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/reflective-knit-hat/2.jpg', 'alt', NULL::text, 'bing-images', 'https://images.lvrcdn.com/Big/c/2025/07/16/96ffb3cf-0a49-404c-a531-5e822bda7ba0/a2c5fa51-c2ec-4cf5-8758-198db88e81fa20250717125634.JPG', 2),
  ('stone-island', 'reflective-mask-jacket', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/reflective-mask-jacket/1.jpg', 'front', NULL::text, 'bing-images', 'https://image-cdn.hypb.st/https://s3.store.hypebeast.com/media/image/28/4f/jacket_12_6-7d46e98ccc8073a891dcc2840eda.jpg?fit=max&w=720&q=90', 1),
  ('stone-island', 'reflective-mask-jacket', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/reflective-mask-jacket/2.jpg', 'alt', NULL::text, 'bing-images', 'https://streetvault.net/cdn/shop/files/3AC92E01-B61C-429F-A539-03BCA24AB261.heic?v=1700644646&width=2831', 2),
  ('stone-island', 'shadow-project-piece', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/shadow-project-piece/1.jpg', 'front', NULL::text, 'bing-images', 'https://www.stoneisland.com/on/demandware.static/-/Library-Sites-library-stone-global/default/dw5f41905c/flp/Archive - shadow/Stone Island Shadow Project_SS_020_39.rgb.jpg', 1),
  ('stone-island', 'shadow-project-piece', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stone-island/shadow-project-piece/2.jpg', 'alt', NULL::text, 'bing-images', 'https://www.stoneisland.com/on/demandware.static/-/Library-Sites-library-stone-global/default/dw981c69b8/flp/Archive - shadow/20_Shadow_crop.jpg', 2),
  ('stussy', '8-ball-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/8-ball-tee/1.jpg', 'front', NULL::text, 'bing-images', 'https://images.stockx.com/images/Stussy-8-Ball-Pigment-Dyed-Tee-Navy-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&q=90&dpr=2&trim=color&updated_at=1738193358', 1),
  ('stussy', '8-ball-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/8-ball-tee/2.jpg', 'alt', NULL::text, 'bing-images', 'https://images.stockx.com/images/Stussy-8-Ball-Pigment-Dyed-Tee-Natural-2-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&q=90&dpr=2&trim=color&updated_at=1712594728?height=78&width=78', 2),
  ('stussy', 'basic-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/basic-tee/1.webp', 'front', NULL::text, 'bing-images', 'https://www.stussy.com/cdn/shop/files/1905000_BLAC_1.jpg?v=1760638172&width=1920', 1),
  ('stussy', 'basic-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/basic-tee/2.webp', 'alt', NULL::text, 'bing-images', 'https://media.endclothing.com/media/f_auto,q_auto:eco,w_1600/prodmedia/media/catalog/product/2/3/23-06-2023-JC_1904870-NAVY_8_1.jpg', 2),
  ('stussy', 'big-logo-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/big-logo-tee/1.jpg', 'front', NULL::text, 'bing-images', 'https://www.citybeach.com/on/demandware.static/-/Sites-fewstoneMaster/default/dwd8194b7f/images/20362417/20362417-02-LT-XL.jpg', 1),
  ('stussy', 'big-logo-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/big-logo-tee/2.jpg', 'alt', NULL::text, 'bing-images', 'https://obs.line-scdn.net/r/ect/ect/image_17017507123298473706c6a6724t12aacea8', 2),
  ('stussy', 'bucket-hat', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/bucket-hat/1.jpg', 'front', NULL::text, 'bing-images', 'https://www.consortium.co.uk/media/catalog/product/cache/1/image/1000x/af097278c5db4767b0fe9bb92fe21690/s/t/stussy-stock-lock-deep-bucket-hat-black-1321175-blk_0000_cat.jpg', 1),
  ('stussy', 'bucket-hat', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/bucket-hat/2.webp', 'alt', NULL::text, 'bing-images', 'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/2/2/22-02-2021_MO_1321023-BLAC_m1_1.jpg', 2),
  ('stussy', 'cardigan', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/cardigan/1.webp', 'front', NULL::text, 'bing-images', 'https://cdn.clothbase.com/uploads/e533150f-00f9-4895-9f4e-1e316a6e7407/black-shaggy-cardigan.jpg', 1),
  ('stussy', 'cardigan', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/cardigan/2.webp', 'alt', NULL::text, 'bing-images', 'https://cdn.clothbase.com/uploads/531fd930-ebd7-4e84-b040-34f09170a0b9/black-brushed-cardigan.jpg', 2),
  ('stussy', 'crown-hoodie', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/crown-hoodie/1.webp', 'front', NULL::text, 'bing-images', 'https://www.culturekings.com.au/cdn/shop/files/02045840-YB001_mens_10_1024x1024.jpg?v=1689825071', 1),
  ('stussy', 'crown-hoodie', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/crown-hoodie/2.jpg', 'alt', NULL::text, 'bing-images', 'https://img.gem.app/864174543/1f/1699035917/streetwear-stussy-stussy-grey-crown-hoodie.jpg', 2),
  ('stussy', 'nike-collab', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/nike-collab/1.jpg', 'front', NULL::text, 'bing-images', 'https://static.nike.com/a/images/w_1280,q_auto,f_auto/3cbe2d86-07c5-4932-80ca-8fb61424a48f/nike-x-stüssy-apparel-accessories-collection-release-date.jpg', 1),
  ('stussy', 'nike-collab', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/nike-collab/2.jpg', 'alt', NULL::text, 'bing-images', 'https://media-photos.depop.com/b1/443233039/repop_46618938_2889404172/2939641289_6e1845b28d4247a3a87a1e1cb87cfd18/P0.jpg', 2),
  ('stussy', 'snapback', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/snapback/1.webp', 'front', NULL::text, 'bing-images', 'https://yenotrading.ca/cdn/shop/products/IMG_8524_1024x1024.jpg?v=1642387820', 1),
  ('stussy', 'snapback', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/snapback/2.jpg', 'alt', NULL::text, 'bing-images', 'https://images.stockx.com/images/Stussy-Trucker-Big-Basic-Snapback-Black.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&q=90&dpr=2&trim=color&updated_at=1716581317', 2),
  ('stussy', 'stock-logo-hoodie', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/stock-logo-hoodie/1.webp', 'front', NULL::text, 'bing-images', 'https://media.endclothing.com/media/f_auto,q_auto:eco,w_1600/prodmedia/media/catalog/product/2/2/22-06-23-TC_118475-BLK_1_1.jpg', 1),
  ('stussy', 'stock-logo-hoodie', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/stock-logo-hoodie/2.webp', 'alt', NULL::text, 'bing-images', 'https://media.endclothing.com/media/f_auto,q_auto:eco,w_1600/prodmedia/media/catalog/product/2/2/22-06-23-TC_118475-BLK_7_1.jpg', 2),
  ('stussy', 'world-tour-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/world-tour-tee/1.jpg', 'front', NULL::text, 'bing-images', 'https://d2cva83hdk3bwc.cloudfront.net/stussy-world-tour-tee-black--1.jpg', 1),
  ('stussy', 'world-tour-tee', 'https://vrvwdagjpttvfvjanbwq.supabase.co/storage/v1/object/public/legit-references/stussy/world-tour-tee/2.png', 'alt', NULL::text, 'bing-images', 'https://img.lazcdn.com/g/p/e96c45bda68da20db0f91dc8d10ac3e2.png_720x720q80.png', 2)
) AS v(brand_slug, model_slug, photo_url, angle, focus, source, source_url, ordering)
JOIN legit_check_brands b ON b.slug = v.brand_slug
JOIN legit_check_models m ON m.brand_id = b.id AND m.slug = v.model_slug
ON CONFLICT (model_id, photo_url) DO NOTHING;

